### ISSUE TITLE
Is there anything missing?

### ISSUE THREAD

**Issue by vylan** [sAleksovski/scrum-board#1]
Hi,

When I try to login with google plus, it redirects to '/signin' after logged in, which's a 404 page.   I wonder If you've missed the implementation of signin?

**Comment by sAleksovski** [comment]
There's no implementation on '/signin'. When I've run the application, it redirected to '/signup', so that's the only endpoint implemented.

**Comment by vylan** [comment]
Thanks for your reply. Here's the error message after I logged in with google plus:

` Whitelabel Error Page
`
```
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jan 17 07:19:30 UTC 2017
There was an unexpected error (type=Not Found, status=404).
/signin
```

I don't know how to redirect to '/signup', could you provide more detailed info?

**Comment by vylan** [comment]
Hi, Are you still there?

**Comment by sAleksovski** [comment]
Hi.
I just tried it, and it always redirected me to /signup, resulting in another redirect to the frontend.

How are you configuring the api keys for google sign in?

**Comment by vylan** [comment]
Works with twitter!  According to this [issue](https://github.com/GabiAxel/spring-social-google/issues/81) , the "spring-social-google" lib may have some problem, which caused can't redirect to signup.

Thanks again.
